version: '3.4'

services:
  db:
    container_name: db
    image: gitlab.jasongallagher.org:4431/root/jasongallagher.org/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${JG_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${JG_DATABASE_PASSWORD}
      - POSTGRES_DB=${JG_DATABASE_DATABASE}
    volumes:
      - 'jg_data:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: exit 0

  app:
    container_name: jasongallagher
    volumes:
      - './public:/src/public'
    ports:
      - '3100:3100'
    env_file: ./.env
    restart: always
    depends_on:
      - db
networks:
  default:
    external:
      name: jg
volumes:
  jg_data: