version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   # environment:
  #     # - NGINX_HOST=foobar.com
  #     # - NGINX_PORT=80

  db:
    container_name: db
#    build:
#      context: ./database
#      dockerfile: Dockerfile-db
    image: gitlab.jasongallagher.org:4431/root/jasongallagher.org/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${JG_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${JG_DATABASE_PASSWORD}
      - POSTGRES_DB=${JG_DATABASE_DATABASE}
    volumes:
      - 'jg_data:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: exit 0

  app:
    container_name: jasongallagher
    build:
      context: ./
      dockerfile: Dockerfile-app
    # image: gitlab.jasongallagher.org:4431/root/jasongallagher.org/app
    volumes:
      - './app:/src/app'
      - './server:/src/server'
      - './config:/src/config'
      - './package.json:/src/package.json'
      - './webpack.config.js:/src/webpack.config.js'
      - './webpack.production.config.js:/src/webpack.production.config.js'
      - './.babelrc:/src/.babelrc'
      - './.eslintrc:/src/.eslintrc'
      - './postcss.config.js:/src/postcss.config.js'
      - './test:/src/test'
      - './public:/src/public'
    ports:
      # - '3000:3000' # browser-sync
      # - '3001:3001' # browser-sync
      - '3100:3100' # app
      - '8888:8888' # webpack-bundle-analyzer
    environment:
      - DATABASE_USERNAME=${JG_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${JG_DATABASE_PASSWORD}
      - DATABASE_DATABASE=${JG_DATABASE_DATABASE}
      - DATABASE_HOST=${JG_DATABASE_HOST}
      - DATABASE_PORT=${JG_DATABASE_PORT}
      - DATABASE_DIALECT=${JG_DATABASE_DIALECT}
      - SESSION_SECRET=${JG_SESSION_SECRET}
      - SESSION_KEY=${JG_SESSION_KEY}
      - GOOGLE_ANALYTICS=${JG_GOOGLE_ANALYTICS}
      - EMAIL_FROM=${JG_EMAIL_FROM}
      - EMAIL_TO=${JG_EMAIL_TO}
      - EMAIL_SUBJECT=${JG_EMAIL_SUBJECT}
      - LIVE_CHAT_ADMIN_NAME=${JG_LIVE_CHAT_ADMIN_NAME}
      - SMS_ACTIVE=${JG_SMS_ACTIVE}
      - SMS_FROM=${JG_SMS_FROM}
      - SMS_TO=${JG_SMS_TO}
      - SMS_SUBJECT=${JG_SMS_SUBJECT}
      - SMTP_HOST=${JG_SMTP_HOST}
      - SMTP_PORT=${JG_SMTP_PORT}
      - SMTP_SECURE=${JG_SMTP_SECURE}
      - SMTP_AUTH_USERNAME=${JG_SMTP_AUTH_USERNAME}
      - SMTP_AUTH_PASSWORD=${JG_SMTP_AUTH_PASSWORD}
      - API_BASE=${JG_API_BASE}
      - NODE_ENV=${NODE_ENV}
    restart: always
    depends_on:
      - db
networks:
  default:
    external:
      name: jg
volumes:
  jg_data: